
IF
	Kit(Player%PN%,c4Monk)
	!LevelLT(Player%PN%,%level%)
	TriggerOverride(Player%PN%,Global("c4MonkAddSkillPoint%level%","Locals",0))
THEN
	RESPONSE #100
		DisplayStringHead(Player%PN%,%get_new_sp%)
		// ActionOverride(Player%PN%,SetGlobal("c4MonkAddSkillPoint%level%","Locals",1))
		// ActionOverride(Player%PN%,IncrementGlobal("c4MonkSkillPoint","Locals",1))
		ReallyForceSpellRES("c4mksp%level%",Player%PN%)
		// Continue()
END
