
IF
	Class(Player%n%,MONK)
	TriggerOverride(Player%n%,Global("c4MonkCheck","Locals",1))
	!LevelLT(Player%n%,%level%)
	TriggerOverride(Player%n%,Global("c4MonkAddSkillPoint%level%","Locals",0))
THEN
	RESPONSE #100
		DisplayStringHead(Player%n%,%get_new_sp%)
		ActionOverride(Player%n%,SetGlobal("c4MonkAddSkillPoint%level%","Locals",1))
		ActionOverride(Player%n%,IncrementGlobal("c4MonkSkillPoint","Locals",1))
		Continue()
END
