
IF
	Kit(Player%PN%,c4Monk)
	TriggerOverride(Player%PN%,Global("c4MonkDialog","Locals",1))
THEN
	RESPONSE #100
		ActionOverride(Player%PN%,StartDialogOverride("c4monkd",Myself))
END

IF
	Kit(Player%PN%,c4Monk)
	TriggerOverride(Player%PN%,Global("c4MonkDialog","Locals",0))
	TriggerOverride(Player%PN%,Global("c4MonkBodyTrainingHLA","Locals",1))
THEN
	RESPONSE #100
		ActionOverride(Player%PN%,StartDialogOverride("c4monkd",Myself))
END
